#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

GREP_AGAINST='ref: refs/heads/master'
grep -q "$GREP_AGAINST" "$GIT_DIR"/HEAD >/dev/null 2>&1 
ON_MASTER=$?
if [ ! -z $ON_MASTER ] ; then
	exit 0
fi

"$GIT_DIR/../misc/compileAll.sh"
exit $?
